apiVersion: v1
kind: Namespace
metadata:
  name: unbound-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
  namespace: unbound-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unbound
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: timwebster9/unbound:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: unbound-udp
  namespace: unbound-demo
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: unbound
  ports:
  - protocol: UDP
    port: 53
    name: dnsudp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP:
---
kind: Service
apiVersion: v1
metadata:
  name: unbound-tcp
  namespace: unbound-demo
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  selector:
    app: unbound
  ports:
  - protocol: TCP
    port: 53
    name: dnstcp
    targetPort: 53
  type: LoadBalancer
  loadBalancerIP: